UPDATE "music_styles" SET "ai_description" = 'BPM 90-110 | Shuffled triplet swing groove | Funk-jazz drums, syncopated hi-hat | Melodic groovy bass, bent notes | Rhodes keys, soul guitar, lush strings | Spoken/sung verses, repeated melodic chorus | Warm voice, legato, vibrato | Thick vocal harmonies, ad-libs | Moderate sensual energy | Intimate, nocturnal, romantic mood | Origins: USA (Memphis, Motown, New Orleans)' WHERE "slug" = 'r-and-b' AND "ai_description" ~ '[^\x01-\x7F]';
--> statement-breakpoint
UPDATE "music_styles" SET "ai_description" = 'Tempo 120-130 BPM. Syncopated groovy rhythm. Percussion: bells, drums, offbeat hi-hats. Steady funk bass line. Guitars/horns: short percussive stabs. Structure: groovy intro, spoken/sung verses, group chorus, instrumental bridge. Vocals: energetic, rhythmic, often talk-singing. Backing vocals: call-and-response. High danceable energy. Festive, convivial, driving mood. Nigerian and West African origin.' WHERE "slug" = 'afrobeat' AND "ai_description" ~ '[^\x01-\x7F]';
--> statement-breakpoint
UPDATE "music_styles" SET "ai_description" = 'BPM 105-110. Syncopated danceable rhythm. Percussion: closed hi-hat, synthetic kicks, crisp claps. Bass: deep pulsing sub-bass. Instruments: melodic piano (4-chord progressions), warm synths. Structure: piano intro, repetitive verses, catchy hook chorus, minimal breakdowns. Vocals: soft sung/spoken, conversational ad-libs. Backing vocals: soft harmonies. Energy: relaxed medium groove. Mood: laid-back urban, nocturnal. Origin: contemporary South African house.' WHERE "slug" = 'amapiano' AND "ai_description" ~ '[^\x01-\x7F]';
--> statement-breakpoint
UPDATE "music_styles" SET "ai_description" = 'BPM 60-90, slow steady rhythm. Minimal or no percussion. Discreet bass, long notes. Acoustic guitar, ukulele, piano, strings. Verse-chorus-bridge. Warm intimate voice. Light backing harmonies. Gentle soothing energy. Introspective, melancholic mood. Timeless international style, no marked regional origin, focus on natural instrumentation and emotional closeness.' WHERE "slug" = 'acoustique' AND "ai_description" ~ '[^\x01-\x7F]';
--> statement-breakpoint
UPDATE "music_styles" SET "ai_description" = '70-80 BPM, syncopated offbeat. Steady kick, light snare, continuous hi-hat. Groovy bass, long notes. Acoustic/electric guitar, warm keys. Classic verse-chorus-bridge. Warm, meditative voice. Harmonic backing vocals, spiritual echo. Moderate, laid-back energy. Meditative, spiritual, zen mood. Jamaican origin, authentic roots reggae.' WHERE "slug" = 'reggae' AND "ai_description" ~ '[^\x01-\x7F]';
--> statement-breakpoint
UPDATE "music_styles" SET "ai_description" = 'BPM 70-90, gospel shuffle/swing. Light percussion: closed hi-hat, syncopated snare. Warm groove bass, walking bass. Hammond organ, soul piano, electric guitar. Intimate verse, anthemic chorus, crescendo bridge. Soul/R&B lead vocal with vibrato, warm lows. Gospel call-and-response choir, 4+ part harmonies. Rising energy, reverent then exalted spiritual mood. African-American origins, USA.' WHERE "slug" = 'gospel' AND "ai_description" ~ '[^\x01-\x7F]';
--> statement-breakpoint
UPDATE "music_styles" SET "ai_description" = 'BPM 85-100. Rhythm: syncopated breakbeat, 4/4 swing. Percussion: 808 drum samples, snappy snare, tight hi-hats. Bass: heavy deep sub. Instruments: cinematic pianos/strings, vinyl scratches, retro samples. Structure: minimal intro, long verses without chorus, spoken bridge, energetic drops. Vocals: natural rap, aggressive flow, poetic prosody, double tracks. Backing: ad-libs, percussive interjections, vocal samples. Energy: raw, defiant, calm-to-explosive contrast. Mood: urban, gritty, introspective. Origin: American rap.' WHERE "slug" = 'rap' AND "ai_description" ~ '[^\x01-\x7F]';
--> statement-breakpoint
UPDATE "music_styles" SET "ai_description" = 'Tempo 100-130 BPM. Syncopated rhythm, danceable groove. Percussion: sharp hi-hats, off-beat kick, crisp claps. Bass: groovy, melodic, prominent. Instruments: brass bursts, percussive guitars, modern synths. Structure: repeated verse-chorus, energetic bridge. Vocals: melodic, conversational, ad-libs. Backing: vocal effects, repetitions, simple harmonies. Energy: very high, festive, danceable. Mood: joyful, urban, celebratory. Origin: West Africa (Nigeria, Ghana).' WHERE "slug" = 'afropop' AND "ai_description" ~ '[^\x01-\x7F]';
--> statement-breakpoint
UPDATE "music_styles" SET "ai_description" = 'Tempo: 60-80 BPM. Rhythm: minimalist, breathing, steady. Percussion: discreet or absent. Bass: deep, spacious, harmonic support. Instruments: strings, piano, acoustic guitar, ambient synths. Structure: long verses, memorable chorus, extended instrumental passages. Vocals: soft, whispered, introspective. Backing: minimal, set back. Energy: low, calm. Mood: respectful silence, vulnerable intimacy. International, timeless contemplative aesthetic.' WHERE "slug" = 'slow' AND "ai_description" ~ '[^\x01-\x7F]';
--> statement-breakpoint
UPDATE "music_styles" SET "ai_description" = '60-70 BPM, expressive rubato, no percussion. Minimal bass, long notes. Lead acoustic piano, optional light strings. Classic verse-chorus-bridge, gradual dynamics. Soft, intimate, slightly trembling voice. Discreet or no backing vocals. Low energy, subtle crescendo. Introspective, nostalgic, contemplative mood. Timeless Western style, European classical influence.' WHERE "slug" = 'ballade-piano' AND "ai_description" ~ '[^\x01-\x7F]';
--> statement-breakpoint
UPDATE "music_styles" SET "ai_description" = '92-110 BPM, swinging shuffle. Syncopated clave, light closed hi-hat. Ghanaian/Ethiopian-style percussion. Melodic walking bass. Horns (trumpet, saxophone), fingerpicked acoustic guitar, piano. Verse-chorus-bridge. Warm voice, clear diction. Harmonized backing vocals, call-and-response. Energetic, danceable. Festive, nostalgic, urban mood. Authentic Ghanaian highlife, 1950s-70s.' WHERE "slug" = 'highlife-retro' AND "ai_description" ~ '[^\x01-\x7F]';
--> statement-breakpoint
UPDATE "music_styles" SET "ai_description" = 'BPM 120-130. Rhythm: syncopated, binary, danceable. Percussion: layered Creole drums, ti-bwa, gwo-ka. Bass: deep groove, syncopated slap bass. Instruments: prominent bass guitar, soft keyboards, occasional horns. Structure: repetitive verse-chorus, short instrumental bridge. Vocals: Creole warmth, fluid pronunciation. Backing: vocal responses, call-and-response exchanges. Energy: festive, sensual, irresistible. Mood: oceanic, tropical, danceable euphoria. Characteristics: Caribbean zouk (Martinique, Guadeloupe).' WHERE "slug" = 'zouk' AND "ai_description" ~ '[^\x01-\x7F]';
