#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { kitVersion, kitVersionLabel } from "./lib/version.mjs";

const root = process.cwd();
const countries = JSON.parse(fs.readFileSync(path.join(root, "config/countries.json"), "utf8"));
const args = Object.fromEntries(
  process.argv.slice(2).map((arg, i, all) => {
    if (!arg.startsWith("--")) return [arg, true];
    const [k, inline] = arg.slice(2).split("=");
    if (inline !== undefined) return [k, inline];
    const next = all[i + 1];
    return [k, next && !next.startsWith("--") ? next : true];
  }),
);
const nonInteractive = Boolean(args["non-interactive"] || args.yes);
const rl = nonInteractive ? null : readline.createInterface({ input, output });

async function ask(label, fallback) {
  if (!rl) return fallback;
  const v = (await rl.question(`${label}${fallback ? ` [${fallback}]` : ""}: `)).trim();
  return v || fallback;
}
function envEscape(v) {
  return String(v).replace(/\n/g, "").replace(/\r/g, "");
}

try {
  console.log(`\nAfrica SaaS Kit ${kitVersionLabel} — Core Setup Wizard\n`);
  console.log(
    "Upstash, les paiements, Cloudflare, Cloudinary et l’application Android/iOS sont optionnels et seront proposés seulement près de la mise en ligne.\n",
  );
  const countryFallback = String(args.country || "CI").toUpperCase();
  const country = String(
    await ask(`Primary country (${Object.keys(countries).join("/")})`, countryFallback),
  ).toUpperCase();
  if (!countries[country]) throw new Error(`Unsupported preset country: ${country}`);
  const preset = countries[country];
  const appName = await ask("Application name", String(args.name || "My Africa SaaS"));
  const appUrl = await ask("Application URL", String(args.url || "http://localhost:3000"));
  const securityLevel = String(
    await ask("Security level (standard/high/maximum)", String(args.security || "high")),
  ).toLowerCase();
  if (!["standard", "high", "maximum"].includes(securityLevel)) throw new Error("Invalid security level");
  const email = String(await ask("Email provider (resend/none)", String(args.email || "resend"))).toLowerCase();
  const storage = "none";
  const boolArg = (value, fallback = true) =>
    value === undefined ? fallback : !["false", "0", "no", "off"].includes(String(value).toLowerCase());
  const googleAuth = boolArg(args["google-auth"], true);
  if (!["resend", "none"].includes(email)) throw new Error("Email provider must be resend or none");
  if (email === "none" && !googleAuth)
    throw new Error(
      "email=none requires Google OAuth (or another auth provider you add yourself) because email/password recovery would be unavailable",
    );
  const emailPasswordEnabled = email === "resend";
  const searchConsole = boolArg(args["search-console"], true);
  const banani = boolArg(args.banani, true);

  const config = {
    version: kitVersion,
    generatedAt: new Date().toISOString(),
    appName,
    appUrl,
    country,
    currency: preset.currency,
    database: "neon",
    auth: "better-auth",
    email,
    emailPasswordEnabled,
    storage,
    cloudinaryEnabled: false,
    upstashEnabled: null,
    googleAuth,
    searchConsole,
    banani,
    securityLevel,
    paymentsEnabled: false,
    mobileAppEnabled: false,
    mobileApp: {
      enabled: false,
      appId: null,
      appName: null,
      productionUrl: null,
      platforms: ["android", "ios"],
      strategy: "webview-hosted",
      bottomNavigation: true,
      prepared: false,
    },
    providers: [],
    defaultProvider: null,
    methods: [],
  };
  fs.writeFileSync(path.join(root, "africa-saas.config.json"), JSON.stringify(config, null, 2) + "\n", { mode: 0o600 });

  const existingEnv = path.join(root, ".env.local");
  if (fs.existsSync(existingEnv) && !args.force) {
    throw new Error(".env.local already exists. Re-run with --force only if you intentionally want to regenerate it.");
  }
  const secret = crypto.randomBytes(48).toString("base64url");
  const cronSecret = crypto.randomBytes(48).toString("base64url");
  const lines = [
    `# Generated by Africa SaaS Kit ${kitVersionLabel}. Never commit this file.`,
    `NEXT_PUBLIC_APP_URL=${envEscape(appUrl)}`,
    `APP_NAME=${envEscape(appName)}`,
    `NEXT_PUBLIC_APP_NAME=${envEscape(appName)}`,
    `DEFAULT_COUNTRY=${country}`,
    "DATABASE_URL=",
    "DATABASE_URL_DIRECT=",
    "DATABASE_SERVICE_URL=",
    `BETTER_AUTH_SECRET=${secret}`,
    `BETTER_AUTH_URL=${envEscape(appUrl)}`,
    `AUTH_EMAIL_PASSWORD_ENABLED=${emailPasswordEnabled ? "true" : "false"}`,
    `AUTH_REQUIRE_EMAIL_VERIFICATION=${emailPasswordEnabled ? "true" : "false"}`,
    "RESEND_API_KEY=",
    "EMAIL_FROM=",
    "GOOGLE_SITE_VERIFICATION=",
    "GOOGLE_CLIENT_ID=",
    "GOOGLE_CLIENT_SECRET=",
    `NEXT_PUBLIC_GOOGLE_AUTH_ENABLED=${googleAuth ? "true" : "false"}`,
    `GOOGLE_SEARCH_CONSOLE_ENABLED=${searchConsole ? "true" : "false"}`,
    `SECURITY_LEVEL=${securityLevel}`,
    `CRON_SECRET=${cronSecret}`,
    "",
    "# Cloudinary is intentionally NOT configured during the core setup.",
    "# If this SaaS needs image uploads, run `npm run cloudinary:setup` in Phase 19.",
    "CLOUDINARY_CLOUD_NAME=",
    "CLOUDINARY_API_KEY=",
    "CLOUDINARY_API_SECRET=",
    "CLOUDINARY_FOLDER=africa-saas-kit",
    "",
    "# Optional infrastructure services",
    "UPSTASH_REDIS_REST_URL=",
    "UPSTASH_REDIS_REST_TOKEN=",
    "TURNSTILE_SECRET_KEY=",
    "NEXT_PUBLIC_TURNSTILE_SITE_KEY=",
    "",
    "# Payments are intentionally NOT configured during the core setup.",
    "# If this SaaS needs payments, run `npm run payments:setup` in Phase 17.",
    "",
    "# Reserved for future storage/observability integrations; setting these alone does nothing.",
    "CLOUDFLARE_R2_ACCOUNT_ID=",
    "CLOUDFLARE_R2_ACCESS_KEY_ID=",
    "CLOUDFLARE_R2_SECRET_ACCESS_KEY=",
    "CLOUDFLARE_R2_BUCKET=",
    "SENTRY_DSN=",
    "NEXT_PUBLIC_POSTHOG_KEY=",
    "",
  ];
  fs.writeFileSync(existingEnv, lines.join("\n"), { mode: 0o600 });

  const generated = path.join(root, "generated");
  fs.mkdirSync(generated, { recursive: true });
  fs.writeFileSync(
    path.join(generated, "setup-summary.json"),
    JSON.stringify({ ...config, credentialsConfigured: false }, null, 2) + "\n",
  );
  console.log("\n✓ africa-saas.config.json generated");
  console.log("✓ .env.local generated with Better Auth + cron secrets");
  console.log("✓ Payments left disabled and optional");
  console.log("\nNext steps:");
  console.log("1. Add DATABASE_URL from Neon to .env.local");
  if (email === "resend")
    console.log("2. Add RESEND_API_KEY and verify EMAIL_FROM (required for email/password auth in production)");
  else console.log("2. Email/password auth disabled; configure Google OAuth before production.");
  console.log("3. Run: npm run setup:check");
  console.log("4. Run: npm run db:generate && npm run db:migrate");
  console.log(
    "5. Continue with /setup-saas. Payments, Cloudflare and Cloudinary will be offered only near deployment.\n",
  );
} finally {
  rl?.close();
}
